In [2]:
import numpy as np

In [38]:
inputs = [[1.3,6.7,2.9,3.2],
          [6.2,9.7,1.9,4.2],
          [3.3,5.2,1.3,6.6]] #Initial multidimesional input e.g. each row represents a single row where each value is represents some aspect of weather like humidity, moisture etc

weights = [[4.4,5.9,3,-3], #Weights for first hidden layer
            [2.1,7.4,2,-3],
            [9.4,4.9,2,-5.9]]

weights1 = [[1,6.9,4.1], #Weights for first hidden layer
            [3.2,1.2,6],
            [4.4,4.1,7,]]

biass = [3,5,2] #Bias for the first hidden layer

biass1 = [5,1,-7]

actual_values = [48,-50,32]

In [39]:
layer1_outputs = np.dot(weights,inputs) #We will get error for this as the shapes of both matrices does not match

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [40]:
#To solve above error we will perform transpose on the weights matrix so that multiplication is possible in multidimesional or multiple layers this is often the case
layer1_outputs = np.dot(inputs,np.array(weights).T) + biass

print(layer1_outputs)

[[47.35 53.51 33.97]
 [80.61 81.   86.83]
 [32.3  33.21 22.16]]


In [42]:
weights1=np.array(weights1).T

print(weights1)

layer2_outputs = (np.dot(layer1_outputs,weights1)) + biass1

print(layer2_outputs)

[[1.  6.9 4.1]
 [3.2 1.2 6. ]
 [4.4 4.1 7. ]]
[[ 373.05   531.204  745.985]
 [ 726.862 1010.412 1417.311]
 [ 241.076  354.578  479.81 ]]
