In [4]:
import numpy as np

In [5]:
inputs = [[1.3,6.7,2.9,3.2],
          [6.2,9.7,1.9,4.2],
          [3.3,5.2,1.3,6.6]] #Initial multidimesional input e.g. each row represents a single row where each value is represents some aspect of weather like humidity, moisture etc

weights = [[4.4,5.9,3,-3], #Weights for first hidden layer
            [2.1,7.4,2,-3],
            [9.4,4.9,2,-5.9]]

weights1 = [[1,6.9,4.1], #Weights for first hidden layer
            [3.2,1.2,6],
            [4.4,4.1,7,]]

biass = [3,5,2] #Bias for the first hidden layer

biass1 = [5,1,-7]

actual_values = [48,-50,32]

In [6]:
layer1_outputs = np.dot(weights,inputs) #We will get error for this as the shapes of both matrices does not match

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [7]:
#To solve above error we will perform transpose on the weights matrix so that multiplication is possible in multidimesional or multiple layers this is often the case
layer1_outputs = np.dot(inputs,np.array(weights).T) + biass

print(layer1_outputs)

[[47.35 53.51 33.97]
 [80.61 81.   86.83]
 [32.3  33.21 22.16]]


In [8]:
weights1=np.array(weights1).T

print(weights1)

layer2_outputs = (np.dot(layer1_outputs,weights1)) + biass1

print(layer2_outputs)

[[1.  3.2 4.4]
 [6.9 1.2 4.1]
 [4.1 6.  7. ]]
[[ 560.846  420.552  658.521]
 [1000.513  877.132 1287.594]
 [ 357.305  277.172  426.401]]


Generally the neural networks contains hundreds even thousands of layers and defining each of the layer separately is not feasible hence we will define classes to simplify the above process for us

Now above layers will need weights and biasis for each layer we will need different weights and biasis, below I will show how to initialize weights and biasis. Generally we choose the values of weights and biasis between a small range such as (-1,1) or (0,1) the reason for this is because the higher weights/biasis will change the output for that layer drastically. As you can see above the difference of layer1 and layer2 output is massive.

`Note:- when we set the weights to small values and set the biasis to zero then sometimes what happens is multiplying by small values can give a very small number and then if we add zero to that then our whole network output becomes zero, which is called a dead network so if you've set the biasis to zero and getting zero output then try setting biasis to non-zero values`

In [20]:
np.random.seed(0)
class layer_creation:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10*np.random.rand(n_inputs,n_neurons) #Multiplied by 0.1 to keep the weights values between 0,1
        self.biasis = np.zeros((1,n_neurons))
    def forward(self,x_input):
        self.outputs = np.dot(x_input,self.weights) + self.biasis
        return self.outputs

In [21]:
layer1 = layer_creation(4,100) # here now we have power to define as many neurons as we can here I am defining 100 neurons
layers2 = layer_creation(100,50) #Note that the input of second layer should math the output of first layers as first layer output is going to be forwarded to the second layer
output1 = layer1.forward(inputs)
output2 = layers2.forward(output1)

In [25]:
print(output1.shape)
print(output2.shape)

(3, 100)
(3, 50)
